=== wardmullins/myngl/bank-account-schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "Record_ID": {
      "$id": "/properties/Record_ID",
      "type": "integer",
      "title": "The Record_id Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Record_ID-myngl-security": {
      "$id": "/properties/Record_ID-myngl-security",
      "type": "string",
      "title": "The Record_id-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Record_Date_Stamp": {
      "$id": "/properties/Record_Date_Stamp",
      "type": "string",
      "title": "The Record_date_stamp Schema ",
      "default": "",
      "examples": [
        "datetime"
      ]
    },
    "Record_Date_Stamp-myngl-security": {
      "$id": "/properties/Record_Date_Stamp-myngl-security",
      "type": "string",
      "title": "The Record_date_stamp-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_ID": {
      "$id": "/properties/Bank_ID",
      "type": "string",
      "title": "The Bank_id Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Bank_ID-myngl-security": {
      "$id": "/properties/Bank_ID-myngl-security",
      "type": "string",
      "title": "The Bank_id-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_Name": {
      "$id": "/properties/Bank_Name",
      "type": "string",
      "title": "The Bank_name Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Bank_Name-myngl-security": {
      "$id": "/properties/Bank_Name-myngl-security",
      "type": "string",
      "title": "The Bank_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_Address": {
      "$id": "/properties/Bank_Address",
      "type": "string",
      "title": "The Bank_address Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Bank_Address-myngl-security": {
      "$id": "/properties/Bank_Address-myngl-security",
      "type": "string",
      "title": "The Bank_address-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_City": {
      "$id": "/properties/Bank_City",
      "type": "string",
      "title": "The Bank_city Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Bank_City-myngl-security": {
      "$id": "/properties/Bank_City-myngl-security",
      "type": "string",
      "title": "The Bank_city-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_Zip": {
      "$id": "/properties/Bank_Zip",
      "type": "integer",
      "title": "The Bank_zip Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Bank_Zip-myngl-security": {
      "$id": "/properties/Bank_Zip-myngl-security",
      "type": "string",
      "title": "The Bank_zip-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_State": {
      "$id": "/properties/Bank_State",
      "type": "string",
      "title": "The Bank_state Schema ",
      "default": "",
      "examples": [
        "alpha "
      ]
    },
    "Bank_State-myngl-security": {
      "$id": "/properties/Bank_State-myngl-security",
      "type": "string",
      "title": "The Bank_state-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_First_Name": {
      "$id": "/properties/Customer_First_Name",
      "type": "string",
      "title": "The Customer_first_name Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Customer_First_Name-myngl-security": {
      "$id": "/properties/Customer_First_Name-myngl-security",
      "type": "string",
      "title": "The Customer_first_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Middle_Init": {
      "$id": "/properties/Customer_Middle_Init",
      "type": "string",
      "title": "The Customer_middle_init Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Customer_Middle_Init-myngl-security": {
      "$id": "/properties/Customer_Middle_Init-myngl-security",
      "type": "string",
      "title": "The Customer_middle_init-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Last_Name": {
      "$id": "/properties/Customer_Last_Name",
      "type": "string",
      "title": "The Customer_last_name Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Customer_Last_Name-myngl-security": {
      "$id": "/properties/Customer_Last_Name-myngl-security",
      "type": "string",
      "title": "The Customer_last_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_SSN": {
      "$id": "/properties/Customer_SSN",
      "type": "integer",
      "title": "The Customer_ssn Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Customer_SSN-myngl-security": {
      "$id": "/properties/Customer_SSN-myngl-security",
      "type": "string",
      "title": "The Customer_ssn-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Name": {
      "$id": "/properties/Customer_Name",
      "type": "integer",
      "title": "The Customer_name Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Customer_Name-myngl-security": {
      "$id": "/properties/Customer_Name-myngl-security",
      "type": "string",
      "title": "The Customer_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Address": {
      "$id": "/properties/Customer_Address",
      "type": "string",
      "title": "The Customer_address Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Customer_Address-myngl-security": {
      "$id": "/properties/Customer_Address-myngl-security",
      "type": "string",
      "title": "The Customer_address-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_City": {
      "$id": "/properties/Customer_City",
      "type": "string",
      "title": "The Customer_city Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Customer_City-myngl-security": {
      "$id": "/properties/Customer_City-myngl-security",
      "type": "string",
      "title": "The Customer_city-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Zip": {
      "$id": "/properties/Customer_Zip",
      "type": "integer",
      "title": "The Customer_zip Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Customer_Zip-myngl-security": {
      "$id": "/properties/Customer_Zip-myngl-security",
      "type": "string",
      "title": "The Customer_zip-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_State": {
      "$id": "/properties/Customer_State",
      "type": "string",
      "title": "The Customer_state Schema ",
      "default": "",
      "examples": [
        "alpha "
      ]
    },
    "Customer_State-myngl-security": {
      "$id": "/properties/Customer_State-myngl-security",
      "type": "string",
      "title": "The Customer_state-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Phone": {
      "$id": "/properties/Customer_Phone",
      "type": "string",
      "title": "The Customer_phone Schema ",
      "default": "",
      "examples": [
        "xxx-xxx-xxxx"
      ]
    },
    "Customer_Phone-myngl-security": {
      "$id": "/properties/Customer_Phone-myngl-security",
      "type": "string",
      "title": "The Customer_phone-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Email": {
      "$id": "/properties/Customer_Email",
      "type": "string",
      "title": "The Customer_email Schema ",
      "default": "",
      "examples": [
        "email"
      ]
    },
    "Customer_Email-myngl-security": {
      "$id": "/properties/Customer_Email-myngl-security",
      "type": "string",
      "title": "The Customer_email-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_Account_Type_1": {
      "$id": "/properties/Bank_Account_Type_1",
      "type": "string",
      "title": "The Bank_account_type_1 Schema ",
      "default": "",
      "examples": [
        "alpha "
      ]
    },
    "Bank_Account_Type_1-myngl-security": {
      "$id": "/properties/Bank_Account_Type_1-myngl-security",
      "type": "string",
      "title": "The Bank_account_type_1-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Good_Standing_Rank": {
      "$id": "/properties/Good_Standing_Rank",
      "type": "integer",
      "title": "The Good_standing_rank Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Good_Standing_Rank-myngl-security": {
      "$id": "/properties/Good_Standing_Rank-myngl-security",
      "type": "string",
      "title": "The Good_standing_rank-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Account_Established_Date": {
      "$id": "/properties/Account_Established_Date",
      "type": "string",
      "title": "The Account_established_date Schema ",
      "default": "",
      "examples": [
        "date"
      ]
    },
    "Account_Established_Date-myngl-security": {
      "$id": "/properties/Account_Established_Date-myngl-security",
      "type": "string",
      "title": "The Account_established_date-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Check_Returned_Count": {
      "$id": "/properties/Check_Returned_Count",
      "type": "integer",
      "title": "The Check_returned_count Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Check_Returned_Count-myngl-security": {
      "$id": "/properties/Check_Returned_Count-myngl-security",
      "type": "string",
      "title": "The Check_returned_count-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Bank_Account_Type_2": {
      "$id": "/properties/Bank_Account_Type_2",
      "type": "string",
      "title": "The Bank_account_type_2 Schema ",
      "default": "",
      "examples": [
        "alpha "
      ]
    },
    "Bank_Account_Type_2-myngl-security": {
      "$id": "/properties/Bank_Account_Type_2-myngl-security",
      "type": "string",
      "title": "The Bank_account_type_2-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    }
  }
}

=== wardmullins/myngl/bank-data.json
{
"Record_ID":1,
"Record_ID-myngl-security": "",
"Record_Date_Stamp":"datetime",
"Record_Date_Stamp-myngl-security": "",
"Bank_ID":"alphanumeric",
"Bank_ID-myngl-security": "",
"Bank_Name":"alphanumeric",
"Bank_Name-myngl-security": "",
"Bank_Address":"alphanumeric",
"Bank_Address-myngl-security": "",
"Bank_Address":"alphanumeric",
"Bank_Address-myngl-security": "",
"Bank_City":"alphanumeric",
"Bank_City-myngl-security": "",
"Bank_Zip":1,
"Bank_Zip-myngl-security": "",
"Bank_State":"alpha ",
"Bank_State-myngl-security": "",
"Customer_First_Name":"alpha",
"Customer_First_Name-myngl-security": "",
"Customer_Middle_Init":"alpha",
"Customer_Middle_Init-myngl-security": "",
"Customer_Last_Name":"alpha",
"Customer_Last_Name-myngl-security": "",
"Customer_SSN":1,
"Customer_SSN-myngl-security": "",
"Customer_Name":1,
"Customer_Name-myngl-security": "",
"Customer_Address":"alphanumeric",
"Customer_Address-myngl-security": "",
"Customer_Address":"alphanumeric",
"Customer_Address-myngl-security": "",
"Customer_City":"alphanumeric",
"Customer_City-myngl-security": "",
"Customer_Zip":1,
"Customer_Zip-myngl-security": "",
"Customer_State":"alpha ",
"Customer_State-myngl-security": "",
"Customer_Phone":"xxx-xxx-xxxx",
"Customer_Phone-myngl-security": "",
"Customer_Email":"email",
"Customer_Email-myngl-security": "",
"Bank_Account_Type_1":"alpha ",
"Bank_Account_Type_1-myngl-security": "",
"Good_Standing_Rank":1,
"Good_Standing_Rank-myngl-security": "",
"Account_Established_Date":"date",
"Account_Established_Date-myngl-security": "",
"Check_Returned_Count":1,
"Check_Returned_Count-myngl-security": "",
"Bank_Account_Type_2":"alpha ",
"Bank_Account_Type_2-myngl-security": "",
"Good_Standing_Rank":1,
"Good_Standing_Rank-myngl-security": "",
"Account_Established_Date":"date",
"Account_Established_Date-myngl-security": "",
"Check_Returned_Count":1 ,"Check_Returned_Count-myngl-security": ""

}

=== wardmullins/myngl/bank-data-without-tags.json
{
"Record_ID":1,
"Record_Date_Stamp":"datetime",
"Bank_ID":"alphanumeric",
"Bank_Name":"alphanumeric",
"Bank_Address":"alphanumeric",
"Bank_Address":"alphanumeric",
"Bank_City":"alphanumeric",
"Bank_Zip":1,
"Bank_State":"alpha ",
"Customer_First_Name":"alpha",
"Customer_Middle_Init":"alpha",
"Customer_Last_Name":"alpha",
"Customer_SSN":1,
"Customer_Name":1,
"Customer_Address":"alphanumeric",
"Customer_Address":"alphanumeric",
"Customer_City":"alphanumeric",
"Customer_Zip":1,
"Customer_State":"alpha ",
"Customer_Phone":"xxx-xxx-xxxx",
"Customer_Email":"email",
"Bank_Account_Type_1":"alpha ",
"Good_Standing_Rank":1,
"Account_Established_Date":"date",
"Check_Returned_Count":1,
"Bank_Account_Type_2":"alpha ",
"Good_Standing_Rank":1,
"Account_Established_Date":"date",
"Check_Returned_Count":1 

}
