=== wardmullins/myngl/consumers-schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "owner": {
      "$id": "/properties/owner",
      "type": "string",
      "title": "The Owner Schema ",
      "default": "",
      "examples": [
        "bob"
      ]
    },
    "owner-myngl-security": {
      "$id": "/properties/owner-myngl-security",
      "type": "string",
      "title": "The Owner-myngl-security Schema ",
      "default": "",
      "examples": [
        "1"
      ]
    },
    "dataset": {
      "$id": "/properties/dataset",
      "type": "string",
      "title": "The Dataset Schema ",
      "default": "",
      "examples": [
        "Bank of America - 3/31/18"
      ]
    },
    "dataset-myngl-security": {
      "$id": "/properties/dataset-myngl-security",
      "type": "string",
      "title": "The Dataset-myngl-security Schema ",
      "default": "",
      "examples": [
        "1"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema ",
      "default": "",
      "examples": [
        "Jane Dpe"
      ]
    },
    "name-myngl-security": {
      "$id": "/properties/name-myngl-security",
      "type": "string",
      "title": "The Name-myngl-security Schema ",
      "default": "",
      "examples": [
        "9"
      ]
    },
    "state": {
      "$id": "/properties/state",
      "type": "string",
      "title": "The State Schema ",
      "default": "",
      "examples": [
        "CA"
      ]
    },
    "state-myngl-security": {
      "$id": "/properties/state-myngl-security",
      "type": "string",
      "title": "The State-myngl-security Schema ",
      "default": "",
      "examples": [
        "5"
      ]
    },
    "city": {
      "$id": "/properties/city",
      "type": "string",
      "title": "The City Schema ",
      "default": "",
      "examples": [
        "San Francisco"
      ]
    },
    "city-myngl-security": {
      "$id": "/properties/city-myngl-security",
      "type": "string",
      "title": "The City-myngl-security Schema ",
      "default": "",
      "examples": [
        "5"
      ]
    },
    "zipcode": {
      "$id": "/properties/zipcode",
      "type": "string",
      "title": "The Zipcode Schema ",
      "default": "",
      "examples": [
        "94102"
      ]
    },
    "zipcode-myngl-security": {
      "$id": "/properties/zipcode-myngl-security",
      "type": "string",
      "title": "The Zipcode-myngl-security Schema ",
      "default": "",
      "examples": [
        "5"
      ]
    },
    "email": {
      "$id": "/properties/email",
      "type": "string",
      "title": "The Email Schema ",
      "default": "",
      "examples": [
        "jane.doe2014@gmail.com"
      ]
    },
    "email-myngl-security": {
      "$id": "/properties/email-myngl-security",
      "type": "string",
      "title": "The Email-myngl-security Schema ",
      "default": "",
      "examples": [
        "7"
      ]
    },
    "birthday": {
      "$id": "/properties/birthday",
      "type": "string",
      "title": "The Birthday Schema ",
      "default": "",
      "examples": [
        "1998-1-31"
      ]
    },
    "birthday-myngl-security": {
      "$id": "/properties/birthday-myngl-security",
      "type": "string",
      "title": "The Birthday-myngl-security Schema ",
      "default": "",
      "examples": [
        "9"
      ]
    },
    "cardnumber": {
      "$id": "/properties/cardnumber",
      "type": "string",
      "title": "The Cardnumber Schema ",
      "default": "",
      "examples": [
        "1111-0000-0000-0000"
      ]
    },
    "cardnumber-myngl-security": {
      "$id": "/properties/cardnumber-myngl-security",
      "type": "string",
      "title": "The Cardnumber-myngl-security Schema ",
      "default": "",
      "examples": [
        "9"
      ]
    },
    "ssn": {
      "$id": "/properties/ssn",
      "type": "string",
      "title": "The Ssn Schema ",
      "default": "",
      "examples": [
        "111-000-0000"
      ]
    },
    "ssn-myngl-security": {
      "$id": "/properties/ssn-myngl-security",
      "type": "string",
      "title": "The Ssn-myngl-security Schema ",
      "default": "",
      "examples": [
        "9"
      ]
    },
    "creditscore": {
      "$id": "/properties/creditscore",
      "type": "string",
      "title": "The Creditscore Schema ",
      "default": "",
      "examples": [
        "750"
      ]
    },
    "creditscore-myngl-security": {
      "$id": "/properties/creditscore-myngl-security",
      "type": "string",
      "title": "The Creditscore-myngl-security Schema ",
      "default": "9",
      "pattern": "^[0-9]$",
      "examples": [
        "8"
      ]
    }
  },
  "required": ["owner", "dataset", "name", "state", "city", "zipcode", "email", "birthday", "cardnumber", "ssn", "creditscore"],
  "indexed-fields": ["state", "city", "zipcode", "creditscore"]
}

=== wardmullins/myngl/consumers-with-tags.json
{
	"owner": "bob",
        "owner-myngl-security": "1" ,
	"dataset": "Bank of America - 3/31/18",
        "dataset-myngl-security": "1",
	"name": "Jane Dpe",
        "name-myngl-security": "9",
	"state": "CA",
        "state-myngl-security": "5",
	"city": "San Francisco",
        "city-myngl-security": "5",
	"zipcode": "94102",
        "zipcode-myngl-security": "5",
	"email": "jane.doe2014@gmail.com",
        "email-myngl-security": "7",
	"birthday": "1998-1-31",
        "birthday-myngl-security": "9",
	"cardnumber": "1111-0000-0000-0000",
        "cardnumber-myngl-security": "9",
	"ssn": "111-000-0000",
        "ssn-myngl-security": "9",
	"creditscore": "750",
        "creditscore-myngl-security": "8"
}
