=== wardmullins/myngl/utility-schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "Record_ID": {
      "$id": "/properties/Record_ID",
      "type": "integer",
      "title": "The Record_id Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Record_ID-myngl-security": {
      "$id": "/properties/Record_ID-myngl-security",
      "type": "string",
      "title": "The Record_id-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Provider_ID": {
      "$id": "/properties/Provider_ID",
      "type": "string",
      "title": "The Provider_id Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Provider_ID-myngl-security": {
      "$id": "/properties/Provider_ID-myngl-security",
      "type": "string",
      "title": "The Provider_id-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Provider_Name": {
      "$id": "/properties/Provider_Name",
      "type": "string",
      "title": "The Provider_name Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Provider_Name-myngl-security": {
      "$id": "/properties/Provider_Name-myngl-security",
      "type": "string",
      "title": "The Provider_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Provider_Address": {
      "$id": "/properties/Provider_Address",
      "type": "string",
      "title": "The Provider_address Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Provider_Address-myngl-security": {
      "$id": "/properties/Provider_Address-myngl-security",
      "type": "string",
      "title": "The Provider_address-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Provider_City": {
      "$id": "/properties/Provider_City",
      "type": "string",
      "title": "The Provider_city Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Provider_City-myngl-security": {
      "$id": "/properties/Provider_City-myngl-security",
      "type": "string",
      "title": "The Provider_city-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Provider_Zip": {
      "$id": "/properties/Provider_Zip",
      "type": "integer",
      "title": "The Provider_zip Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Provider_Zip-myngl-security": {
      "$id": "/properties/Provider_Zip-myngl-security",
      "type": "string",
      "title": "The Provider_zip-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Provider_State": {
      "$id": "/properties/Provider_State",
      "type": "string",
      "title": "The Provider_state Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Provider_State-myngl-security": {
      "$id": "/properties/Provider_State-myngl-security",
      "type": "string",
      "title": "The Provider_state-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_First_Name": {
      "$id": "/properties/Customer_First_Name",
      "type": "string",
      "title": "The Customer_first_name Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Customer_First_Name-myngl-security": {
      "$id": "/properties/Customer_First_Name-myngl-security",
      "type": "string",
      "title": "The Customer_first_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Middle_Init": {
      "$id": "/properties/Customer_Middle_Init",
      "type": "string",
      "title": "The Customer_middle_init Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Customer_Middle_Init-myngl-security": {
      "$id": "/properties/Customer_Middle_Init-myngl-security",
      "type": "string",
      "title": "The Customer_middle_init-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Last_Name": {
      "$id": "/properties/Customer_Last_Name",
      "type": "string",
      "title": "The Customer_last_name Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Customer_Last_Name-myngl-security": {
      "$id": "/properties/Customer_Last_Name-myngl-security",
      "type": "string",
      "title": "The Customer_last_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_SSN": {
      "$id": "/properties/Customer_SSN",
      "type": "integer",
      "title": "The Customer_ssn Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Customer_SSN-myngl-security": {
      "$id": "/properties/Customer_SSN-myngl-security",
      "type": "string",
      "title": "The Customer_ssn-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Name": {
      "$id": "/properties/Customer_Name",
      "type": "integer",
      "title": "The Customer_name Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Customer_Name-myngl-security": {
      "$id": "/properties/Customer_Name-myngl-security",
      "type": "string",
      "title": "The Customer_name-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Address": {
      "$id": "/properties/Customer_Address",
      "type": "string",
      "title": "The Customer_address Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Customer_Address-myngl-security": {
      "$id": "/properties/Customer_Address-myngl-security",
      "type": "string",
      "title": "The Customer_address-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_City": {
      "$id": "/properties/Customer_City",
      "type": "string",
      "title": "The Customer_city Schema ",
      "default": "",
      "examples": [
        "alphanumeric"
      ]
    },
    "Customer_City-myngl-security": {
      "$id": "/properties/Customer_City-myngl-security",
      "type": "string",
      "title": "The Customer_city-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Zip": {
      "$id": "/properties/Customer_Zip",
      "type": "integer",
      "title": "The Customer_zip Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "Customer_Zip-myngl-security": {
      "$id": "/properties/Customer_Zip-myngl-security",
      "type": "string",
      "title": "The Customer_zip-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_State": {
      "$id": "/properties/Customer_State",
      "type": "string",
      "title": "The Customer_state Schema ",
      "default": "",
      "examples": [
        "alpha "
      ]
    },
    "Customer_State-myngl-security": {
      "$id": "/properties/Customer_State-myngl-security",
      "type": "string",
      "title": "The Customer_state-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Phone": {
      "$id": "/properties/Customer_Phone",
      "type": "string",
      "title": "The Customer_phone Schema ",
      "default": "",
      "examples": [
        "xxx-xxx-xxxx"
      ]
    },
    "Customer_Phone-myngl-security": {
      "$id": "/properties/Customer_Phone-myngl-security",
      "type": "string",
      "title": "The Customer_phone-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Customer_Email": {
      "$id": "/properties/Customer_Email",
      "type": "string",
      "title": "The Customer_email Schema ",
      "default": "",
      "examples": [
        "email"
      ]
    },
    "Customer_Email-myngl-security": {
      "$id": "/properties/Customer_Email-myngl-security",
      "type": "string",
      "title": "The Customer_email-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Invoice_Amount": {
      "$id": "/properties/Invoice_Amount",
      "type": "string",
      "title": "The Invoice_amount Schema ",
      "default": "",
      "examples": [
        "currency"
      ]
    },
    "Invoice_Amount-myngl-security": {
      "$id": "/properties/Invoice_Amount-myngl-security",
      "type": "string",
      "title": "The Invoice_amount-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Invoice_Date": {
      "$id": "/properties/Invoice_Date",
      "type": "string",
      "title": "The Invoice_date Schema ",
      "default": "",
      "examples": [
        "date"
      ]
    },
    "Invoice_Date-myngl-security": {
      "$id": "/properties/Invoice_Date-myngl-security",
      "type": "string",
      "title": "The Invoice_date-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Payment_Due_Date": {
      "$id": "/properties/Payment_Due_Date",
      "type": "string",
      "title": "The Payment_due_date Schema ",
      "default": "",
      "examples": [
        "date"
      ]
    },
    "Payment_Due_Date-myngl-security": {
      "$id": "/properties/Payment_Due_Date-myngl-security",
      "type": "string",
      "title": "The Payment_due_date-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Payment_Received": {
      "$id": "/properties/Payment_Received",
      "type": "string",
      "title": "The Payment_received Schema ",
      "default": "",
      "examples": [
        "alpha"
      ]
    },
    "Payment_Received-myngl-security": {
      "$id": "/properties/Payment_Received-myngl-security",
      "type": "string",
      "title": "The Payment_received-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Payment_Received_Date": {
      "$id": "/properties/Payment_Received_Date",
      "type": "string",
      "title": "The Payment_received_date Schema ",
      "default": "",
      "examples": [
        "date"
      ]
    },
    "Payment_Received_Date-myngl-security": {
      "$id": "/properties/Payment_Received_Date-myngl-security",
      "type": "string",
      "title": "The Payment_received_date-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    },
    "Balance_Due": {
      "$id": "/properties/Balance_Due",
      "type": "string",
      "title": "The Balance_due Schema ",
      "default": "",
      "examples": [
        "currency"
      ]
    },
    "Balance_Due-myngl-security": {
      "$id": "/properties/Balance_Due-myngl-security",
      "type": "string",
      "title": "The Balance_due-myngl-security Schema ",
      "default": "",
      "examples": [
        ""
      ]
    }
  },
  "required": [ "Balance_Due", "Customer_Address", "Customer_City", "Customer_Email", "Customer_First_Name", "Customer_Last_Name", "Customer_Middle_Init", "Customer_Name", "Customer_Phone", "Customer_SSN", "Customer_State", "Customer_Zip", "Invoice_Amount", "Invoice_Date", "Payment_Due_Date", "Payment_Received", "Payment_Received_Date", "Provider_Address", "Provider_City", "Provider_ID", "Provider_Name", "Provider_State", "Provider_Zip", "Record_ID" ],
  "indexed-fields": ["Customer_SSN", "Customer_Name", "Customer_First_Name", "Customer_Last_Name", "Customer_Address"]
}

=== wardmullins/myngl/utility-data.json
{
"Record_ID":  1,
"Record_ID-myngl-security": "",
"Provider_ID":  "alphanumeric",
"Provider_ID-myngl-security": "",
"Provider_Name":  "alphanumeric",
"Provider_Name-myngl-security": "",
"Provider_Address":  "alphanumeric",
"Provider_Address-myngl-security": "",
"Provider_Address":  "alphanumeric",
"Provider_Address-myngl-security": "",
"Provider_City":  "alphanumeric",
"Provider_City-myngl-security": "",
"Provider_Zip":  1,
"Provider_Zip-myngl-security": "",
"Provider_State":  "alpha",
"Provider_State-myngl-security": "",
"Customer_First_Name":  "alpha",
"Customer_First_Name-myngl-security": "",
"Customer_Middle_Init":  "alpha",
"Customer_Middle_Init-myngl-security": "",
"Customer_Last_Name":  "alpha",
"Customer_Last_Name-myngl-security": "",
"Customer_SSN":  1,
"Customer_SSN-myngl-security": "",
"Customer_Name":  1,
"Customer_Name-myngl-security": "",
"Customer_Address":  "alphanumeric",
"Customer_Address-myngl-security": "",
"Customer_Address":  "alphanumeric",
"Customer_Address-myngl-security": "",
"Customer_City":  "alphanumeric",
"Customer_City-myngl-security": "",
"Customer_Zip":  1,
"Customer_Zip-myngl-security": "",
"Customer_State":  "alpha ",
"Customer_State-myngl-security": "",
"Customer_Phone":  "xxx-xxx-xxxx",
"Customer_Phone-myngl-security": "",
"Customer_Email":  "email" ,
"Customer_Email-myngl-security": "",
"Invoice_Amount":  "currency",
"Invoice_Amount-myngl-security": "",
"Invoice_Date":  "date",
"Invoice_Date-myngl-security": "",
"Payment_Due_Date":  "date",
"Payment_Due_Date-myngl-security": "",
"Payment_Received":  "alpha",
"Payment_Received-myngl-security": "",
"Payment_Received_Date":  "date",
"Payment_Received_Date-myngl-security": "",
"Balance_Due":  "currency",
"Balance_Due-myngl-security": ""
}

=== wardmullins/myngl/utility-data-without-tags.json
{
"Record_ID":  1,
"Provider_ID":  "alphanumeric",
"Provider_Name":  "alphanumeric",
"Provider_Address":  "alphanumeric",
"Provider_Address":  "alphanumeric",
"Provider_City":  "alphanumeric",
"Provider_Zip":  1,
"Provider_State":  "alpha",
"Customer_First_Name":  "alpha",
"Customer_Middle_Init":  "alpha",
"Customer_Last_Name":  "alpha",
"Customer_SSN":  1,
"Customer_Name":  1,
"Customer_Address":  "alphanumeric",
"Customer_Address":  "alphanumeric",
"Customer_City":  "alphanumeric",
"Customer_Zip":  1,
"Customer_State":  "alpha ",
"Customer_Phone":  "xxx-xxx-xxxx",
"Customer_Email":  "email" ,
"Invoice_Amount":  "currency",
"Invoice_Date":  "date",
"Payment_Due_Date":  "date",
"Payment_Received":  "alpha",
"Payment_Received_Date":  "date",
"Balance_Due":  "currency"
}
